Imports below.

In [30]:
import pandas as pd                 #importing panda library.
from pathlib import Path            #importing to create folder later!

loading up base dataset to use.

In [31]:
processed_df = pd.read_csv("../../data/processed/movies_metadata.csv") # reads processed csv file to use as our base dataset

In [32]:
processed_df.info() #inspecting columns of base dataset

<class 'pandas.DataFrame'>
RangeIndex: 45466 entries, 0 to 45465
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            45463 non-null  float64
 1   release_date  45376 non-null  str
 2   budget        45466 non-null  str
 3   revenue       45460 non-null  float64
 4   runtime       45203 non-null  float64
 5   popularity    45460 non-null  float64
dtypes: float64(4), str(2)
memory usage: 2.1 MB

In [33]:
raw_df = pd.read_csv("../../data/raw/movies_metadata.csv") #loaded up raw dataframe to retrieve useful columns to merge into processed.
credits_processed_df = pd.read_csv("../../data/processed/credits.csv")
movies_processed_df = pd.read_csv("../../data/processed/movie_text.csv")
nested_metadata_processed_df = pd.read_csv("../../data/processed/nested_metadata.csv")

/var/folders/4j/5hl0kjh1529gl0sgpv5h03_00000gn/T/ipykernel_37089/2862976473.py:1: DtypeWarning: Columns (10: popularity) have mixed types. Specify dtype option on import or set low_memory=False.
  raw_df = pd.read_csv("../../data/raw/movies_metadata.csv") #loaded up raw dataframe to retrieve useful columns to merge into processed.

In [34]:
raw_df.columns.tolist() #inspecting which columns i am going to use.

['adult',
 'belongs_to_collection',
 'budget',
 'genres',
 'homepage',
 'id',
 'imdb_id',
 'original_language',
 'original_title',
 'overview',
 'popularity',
 'poster_path',
 'production_companies',
 'production_countries',
 'release_date',
 'revenue',
 'runtime',
 'spoken_languages',
 'status',
 'tagline',
 'title',
 'video',
 'vote_average',
 'vote_count']

After inspecting both raw and processed they do contain the same information.

In [35]:
raw_df.info

<bound method DataFrame.info of        adult                              belongs_to_collection    budget  \
0      False  {'id': 10194, 'name': 'Toy Story Collection', ...  30000000
1      False                                                NaN  65000000
2      False  {'id': 119050, 'name': 'Grumpy Old Men Collect...         0
3      False                                                NaN  16000000
4      False  {'id': 96871, 'name': 'Father of the Bride Col...         0
...      ...                                                ...       ...
45461  False                                                NaN         0
45462  False                                                NaN         0
45463  False                                                NaN         0
45464  False                                                NaN         0
45465  False                                                NaN         0

                                                  genres  \
0      [{'id': 16, 'name': 'Animation'}, {'id': 35, '...
1      [{'id': 12, 'name': 'Adventure'}, {'id': 14, '...
2      [{'id': 10749, 'name': 'Romance'}, {'id': 35, ...
3      [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...
4                         [{'id': 35, 'name': 'Comedy'}]
...                                                  ...
45461  [{'id': 18, 'name': 'Drama'}, {'id': 10751, 'n...
45462                      [{'id': 18, 'name': 'Drama'}]
45463  [{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...
45464                                                 []
45465                                                 []

                                   homepage      id    imdb_id  \
0      http://toystory.disney.com/toy-story     862  tt0114709
1                                       NaN    8844  tt0113497
2                                       NaN   15602  tt0113228
3                                       NaN   31357  tt0114885
4                                       NaN   11862  tt0113041
...                                     ...     ...        ...
45461  http://www.imdb.com/title/tt6209470/  439050  tt6209470
45462                                   NaN  111109  tt2028550
45463                                   NaN   67758  tt0303758
45464                                   NaN  227506  tt0008536
45465                                   NaN  461257  tt6980792

      original_language               original_title  \
0                    en                    Toy Story
1                    en                      Jumanji
2                    en             Grumpier Old Men
3                    en            Waiting to Exhale
4                    en  Father of the Bride Part II
...                 ...                          ...
45461                fa                      رگ خواب
45462                tl          Siglo ng Pagluluwal
45463                en                     Betrayal
45464                en          Satana likuyushchiy
45465                en                     Queerama

                                                overview  ... release_date  \
0      Led by Woody, Andy's toys live happily in his ...  ...   1995-10-30
1      When siblings Judy and Peter discover an encha...  ...   1995-12-15
2      A family wedding reignites the ancient feud be...  ...   1995-12-22
3      Cheated on, mistreated and stepped on, the wom...  ...   1995-12-22
4      Just when George Banks has recovered from his ...  ...   1995-02-10
...                                                  ...  ...          ...
45461        Rising and falling between a man and woman.  ...          NaN
45462  An artist struggles to finish his work while a...  ...   2011-11-17
45463  When one of her hits goes wrong, a professiona...  ...   2003-08-01
45464  In a small town live two brothers, one a minis...  ...   1917-10-21
45465  50 years after decriminalisation of homosexual...  ...   2017-06-09

           revenue runtime                                   spoken_languages  \
0      373554033.0    81.0           [{'iso_639_1': 'en', 'name': 'English'}]
1      262797249.0   104.0  [{'iso_639_1': 'en', 'name': 'English'}, {'iso...
2              0.0   101.0           [{'iso_639_1': 'en', 'name': 'English'}]
3       81452156.0   127.0           [{'iso_639_1': 'en', 'name': 'English'}]
4       76578911.0   106.0           [{'iso_639_1': 'en', 'name': 'English'}]
...            ...     ...                                                ...
45461          0.0    90.0             [{'iso_639_1': 'fa', 'name': 'فارسی'}]
45462          0.0   360.0                  [{'iso_639_1': 'tl', 'name': ''}]
45463          0.0    90.0           [{'iso_639_1': 'en', 'name': 'English'}]
45464          0.0    87.0                                                 []
45465          0.0    75.0           [{'iso_639_1': 'en', 'name': 'English'}]

         status                                            tagline  \
0      Released                                                NaN
1      Released          Roll the dice and unleash the excitement!
2      Released  Still Yelling. Still Fighting. Still Ready for...
3      Released  Friends are the people who let you be yourself...
4      Released  Just When His World Is Back To Normal... He's ...
...         ...                                                ...
45461  Released         Rising and falling between a man and woman
45462  Released                                                NaN
45463  Released                             A deadly game of wits.
45464  Released                                                NaN
45465  Released                                                NaN

                             title  video vote_average vote_count
0                        Toy Story  False          7.7     5415.0
1                          Jumanji  False          6.9     2413.0
2                 Grumpier Old Men  False          6.5       92.0
3                Waiting to Exhale  False          6.1       34.0
4      Father of the Bride Part II  False          5.7      173.0
...                            ...    ...          ...        ...
45461                       Subdue  False          4.0        1.0
45462          Century of Birthing  False          9.0        3.0
45463                     Betrayal  False          3.8        6.0
45464             Satan Triumphant  False          0.0        0.0
45465                     Queerama  False          0.0        0.0

[45466 rows x 24 columns]>

In [36]:
rating_data = raw_df.loc[:, ["id", "vote_average", "vote_count"]].copy() #creating duplicate df from raw_df with filtered columns.
credits_data = credits_processed_df.loc[:, ['id','director', 'cast_size', 'crew_size']].copy()
movies_data = movies_processed_df.loc[:, ['id','title','original_title','overview','original_language','status']].copy()
nested_data = nested_metadata_processed_df.loc[: , ['id','original_title','release_date','genres','production_companies','production_countries','spoken_languages']].copy()

rating_data.info() #id is a string so i will convert into int.

<class 'pandas.DataFrame'>
RangeIndex: 45466 entries, 0 to 45465
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            45466 non-null  str
 1   vote_average  45460 non-null  float64
 2   vote_count    45460 non-null  float64
dtypes: float64(2), str(1)
memory usage: 1.0 MB

3 +5 + 6 + 2 + 6

In [52]:
nested_data.info

<bound method DataFrame.info of            id               original_title release_date  \
0         862                    Toy Story   1995-10-30
1        8844                      Jumanji   1995-12-15
2       15602             Grumpier Old Men   1995-12-22
3       31357            Waiting to Exhale   1995-12-22
4       11862  Father of the Bride Part II   1995-02-10
...       ...                          ...          ...
45428  439050                      رگ خواب          NaN
45429  111109          Siglo ng Pagluluwal   2011-11-17
45430   67758                     Betrayal   2003-08-01
45431  227506          Satana likuyushchiy   1917-10-21
45432  461257                     Queerama   2017-06-09

                         genres  \
0       Animation|Comedy|Family
1      Adventure|Fantasy|Family
2                Romance|Comedy
3          Comedy|Drama|Romance
4                        Comedy
...                         ...
45428              Drama|Family
45429                     Drama
45430     Action|Drama|Thriller
45431                       NaN
45432                       NaN

                                    production_companies  \
0                                Pixar Animation Studios
1      TriStar Pictures|Teitler Film|Interscope Commu...
2                            Warner Bros.|Lancaster Gate
3                 Twentieth Century Fox Film Corporation
4              Sandollar Productions|Touchstone Pictures
...                                                  ...
45428                                                NaN
45429                                        Sine Olivia
45430                            American World Pictures
45431                                          Yermoliev
45432                                                NaN

           production_countries  spoken_languages
0      United States of America           English
1      United States of America  English|Français
2      United States of America           English
3      United States of America           English
4      United States of America           English
...                         ...               ...
45428                      Iran             فارسی
45429               Philippines               NaN
45430  United States of America           English
45431                    Russia               NaN
45432            United Kingdom           English

[45433 rows x 7 columns]>

In [37]:
processed_df["id"].duplicated().sum() #duplicate sum of processed dataframe filtered with just id

np.int64(32)

In [38]:
rating_data["id"].duplicated().sum() #raw dataframe filtered with just id

np.int64(30)

In [39]:
rating_data.loc[rating_data['id'].duplicated(keep=False)]

           id  vote_average  vote_count
676    105045           5.0         1.0
838    132641           0.0         0.0
949     22649           6.2        29.0
1465   105045           5.0         1.0
2564    84198           6.9         7.0
4114    10991           6.0       143.0
4356   110428           7.0        20.0
5130    15028           4.9        89.0
5535    12600           5.7        82.0
5710   109962           4.9         7.0
5865     4912           6.6       281.0
7345     5511           7.9       187.0
8068    23305           6.3        15.0
9165     5511           7.9       187.0
9327    23305           6.3        15.0
9576    69234           5.0         3.0
10419   14788           6.4        36.0
11155   77221           5.9        77.0
11342   13209           6.7        27.0
12066   14788           6.4        36.0
13220  159849           5.0         1.0
13261  141971           6.7         3.0
13375  141971           6.7         3.0
13603  168538           4.7         3.0
13946   97995           5.6         4.0
14000   18440           5.0         5.0
14012   11115           5.2        22.0
15074   22649           6.2        29.0
15702   42495           8.0         3.0
15765   13209           6.7        27.0
16167   99080           0.0         0.0
16764  141971           6.7         3.0
17229   25541           7.1        21.0
19890  119916           0.0         0.0
19925  152795           6.4       165.0
20843   77221           5.9        77.0
20899  109962           4.9         7.0
21116   84198           6.9         7.0
21165  119916           0.0         0.0
21854  152795           6.4       165.0
22151   18440           5.0         5.0
23044   25541           7.1        21.0
23534  110428           7.0        20.0
24164  265189           6.8       255.0
24844   11115           5.2        22.0
26625   69234           5.0         3.0
28860  168538           4.7         3.0
29374   42495           8.0         3.0
30001  132641           0.0         0.0
33184  298721           4.4        50.0
33743   15028           4.9        90.0
33826    4912           6.6       281.0
35798  159849           5.0         1.0
38871   99080           0.0         0.0
40040  298721           4.4        50.0
40276   97995           5.6         4.0
44821   10991           6.0       144.0
44826   12600           5.7        82.0
45265  265189           6.8       255.0

comparing both dataframes below to see if they have similar information. Might drop duplicate rows but waiting on jasper's input. We might have to convert id back into an integer instead of having it floating for the processed dataframe.

In [40]:
#processed_df.loc[676]
processed_df.loc[1465]

id                105045.0
release_date    1995-02-16
budget                   0
revenue                0.0
runtime              115.0
popularity        0.122178
Name: 1465, dtype: object

In [41]:
#rating_data.loc[676]
rating_data.loc[1465]

id              105045
vote_average       5.0
vote_count         1.0
Name: 1465, dtype: object

In [42]:
processed_df.loc[processed_df['id'].duplicated(keep=False)]

             id release_date    budget     revenue  runtime  popularity
676    105045.0   1995-02-16         0         0.0    115.0    0.122178
838    132641.0   1953-04-29         0         0.0     89.0    0.096079
949     22649.0   1932-12-08         4        25.0     89.0    1.914697
1465   105045.0   1995-02-16         0         0.0    115.0    0.122178
2564    84198.0   2012-03-22         0         0.0     84.0    0.501046
...         ...          ...       ...         ...      ...         ...
40040  298721.0   2015-09-02    980000         0.0    122.0    2.535419
40276   97995.0   1921-02-06         0         0.0     62.0    0.141558
44821   10991.0   2000-07-08  16000000  68411275.0     93.0    6.480376
44826   12600.0   2001-07-06         0  28023563.0     75.0    6.080108
45265  265189.0   2014-08-15         0   1359497.0    118.0   12.165685

[62 rows x 6 columns]

Standardizing `processed_df` which was floating at first but converted it into integer datatype. Doing the same thing `rating_data` since the `id` datatype is a string instead of integer to merge them. Where the string datatype comes from is from the raw dataset which `id` was a string.

In [43]:
processed_df['id'] = processed_df['id'].astype('Int64') #converting datatype from floating to int
rating_data['id'] = pd.to_numeric(rating_data['id'], errors='coerce').astype('Int64') #converting datatype from string to int

print(rating_data['id'].dtype)
print(processed_df['id'].dtype)

Int64
Int64

dropping duplicate rows in `id` using a for loop in both the processed dataset and the raw dataset as well which is `rating_data`. Next step will be to merge both datasets so I can have 2 additional columns in the `processed_df`

In [44]:

for data in [processed_df,rating_data]:
    rows_before = len(data) #taking rows before 

    data.drop_duplicates(subset='id',keep='first',inplace= True) #dropping duplicate rows with same id

    rows_after =len(data)

    print(f"Rows dropped: {rows_before - rows_after}" ) #Printed about 32 rows dropped at the time now it's 0.

Rows dropped: 32
Rows dropped: 32

In [45]:
#Checking for duplicate sums in id.
print(rating_data['id'].duplicated().sum()) 
print(processed_df['id'].duplicated().sum())

0
0

Removing NA from both datasets before merging

In [46]:
for column in [processed_df,rating_data]: 
    column.dropna(subset='id',inplace=True)

#Checking sum of NA values in id
print(f"NA values in id column for rating_data is {rating_data['id'].isna().sum()}") 
print(f"NA values in id column for processed_df is {processed_df['id'].isna().sum()}")

NA values in id column for rating_data is 0
NA values in id column for processed_df is 0

In [47]:
merged_df = processed_df.merge(rating_data,on='id',how='left',validate='one_to_one')

In [48]:
print((merged_df['vote_count']== 0).sum())

2896

In [49]:
print((merged_df['vote_count'].isna().sum()))

3