In [68]:
import pandas as pd #imported panda library to use commands.

#1 INSPECT FOLLOWING COLUMNS

- Loaded in files for DataFrame
- Created a list with the filtered columns.
- Made a copy of the filtered_columns

In [69]:
df=pd.read_csv('movies_metadata.csv')


filtered_columns = ['title', 'original_title', 'overview' ,'tagline' , 'original_language' , 'status'] #Since tagline had a bunch of NA values i removed the column as a whole.


clean_data = df[filtered_columns].copy() # makes a separate version of filtered data.

/var/folders/4j/5hl0kjh1529gl0sgpv5h03_00000gn/T/ipykernel_10769/87443338.py:1: DtypeWarning: Columns (10: popularity) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv('movies_metadata.csv')

- Prints out the missing data from the six columns

In [70]:
missing_values = clean_data.isna().sum() #checks what's missing from each column.

print(missing_values) # prints missing data from each column.

title                    6
original_title           0
overview               954
tagline              25054
original_language       11
status                  87
dtype: int64

#2 REMOVE UNNECESSARY WHITESPACE

- iterating through each filtered column to remove each string that has unnecessary white space from text value.

In [71]:
for column in filtered_columns:
    clean_data[column] = clean_data[column].str.strip() #.str treats each string value from the column as a string. 
                                                        # and strip remove unnecessary whitespace from every text value

#3 STANDARDIZING MISISNG AND PLACEHOLDER VALUES

In [72]:
clean_data.isna().sum() #having 25k nulls in tagline could create problems so i remove column!

title                    6
original_title           0
overview               954
tagline              25054
original_language       11
status                  87
dtype: int64

Creating new filtered column, with new clean data set.

In [73]:
filtered_columns = ['title', 'original_title', 'overview' , 'original_language' , 'status','id'] #Since tagline had a bunch of NA values i removed the column as a whole.

clean_data = df[filtered_columns].copy() # makes a separate version of filtered data.

In [74]:
for column in clean_data:
    duplicate_count = clean_data[column].duplicated().sum()
    print(f"Duplicates found in column {column}: {duplicate_count}")

Duplicates found in column title: 3188
Duplicates found in column original_title: 2093
Duplicates found in column overview: 1158
Duplicates found in column original_language: 45373
Duplicates found in column status: 45459
Duplicates found in column id: 30

In [75]:
print(clean_data['original_title'].duplicated().sum())

2093

- Parameters filter out the title, original_title, and id
- You see that there is duplicate id's in the dataframe generated below
- the keep false subset just shows EVERY duplicate

In [ ]:
clean_data.loc[clean_data.duplicated(keep=False), ['title', 'original_title','id']] #first parameter looks for rows with duplicates, and second parameter i filtered two columns, and third it shows the duplicate row

,title,original_title,id
676,The Promise,Das Versprechen,105045
838,Wife,Tsuma,132641
949,A Farewell to Arms,A Farewell to Arms,22649
1465,The Promise,Das Versprechen,105045
2564,A Place at the Table,A Place at the Table,84198
4114,Pokémon: Spell of the Unknown,Pokémon 3: The Movie,10991
4356,Camille Claudel 1915,Camille Claudel 1915,110428
5130,Clockstoppers,Clockstoppers,15028
5535,Pokémon 4Ever: Celebi - Voice of the Forest,劇場版ポケットモンスター セレビィ 時を越えた遭遇（であい）,12600
5710,Rich and Famous,Rich and Famous,109962
5865,Confessions of a Dangerous Mind,Confessions of a Dangerous Mind,4912
7345,Le Samouraï,Le Samouraï,5511
8068,The Warrior,The Warrior,23305
9165,Le Samouraï,Le Samouraï,5511
9327,The Warrior,The Warrior,23305
9576,The Phantom of the Opera,The Phantom of the Opera,69234
10419,Bubble,Bubble,14788
11155,Black Gold,Black Gold,77221
11342,Offside,Offside,13209
12066,Bubble,Bubble,14788
13220,Why We Fight: Divide and Conquer,Why We Fight: Divide and Conquer,159849
13261,Blackout,Blackout,141971
13375,Blackout,Blackout,141971
13603,"Nana, the True Key of Pleasure",Nana,168538
13946,Seven Years Bad Luck,Seven Years Bad Luck,97995
14000,Days of Darkness,Days of Darkness,18440
14012,Deal,Deal,11115
15074,A Farewell to Arms,A Farewell to Arms,22649
15702,King Lear,King Lear,42495
15765,Offside,Offside,13209
16167,The Viking,The Viking,99080
16764,Blackout,Blackout,141971
17229,Brotherhood,Broderskab,25541
19890,The Tempest,The Tempest,119916
19925,The Congress,The Congress,152795
20843,Black Gold,Black Gold,77221
20899,Rich and Famous,Rich and Famous,109962
21116,A Place at the Table,A Place at the Table,84198
21165,The Tempest,The Tempest,119916
21854,The Congress,The Congress,152795
22151,Days of Darkness,Days of Darkness,18440
23044,Brotherhood,Broderskab,25541
23534,Camille Claudel 1915,Camille Claudel 1915,110428
24164,Force Majeure,Turist,265189
24844,Deal,Deal,11115
26625,The Phantom of the Opera,The Phantom of the Opera,69234
28860,"Nana, the True Key of Pleasure",Nana,168538
29374,King Lear,King Lear,42495
30001,Wife,Tsuma,132641
33184,Cemetery of Splendour,รักที่ขอนแก่น,298721
33743,Clockstoppers,Clockstoppers,15028
33826,Confessions of a Dangerous Mind,Confessions of a Dangerous Mind,4912
35798,Why We Fight: Divide and Conquer,Why We Fight: Divide and Conquer,159849
38871,The Viking,The Viking,99080
40040,Cemetery of Splendour,รักที่ขอนแก่น,298721
40276,Seven Years Bad Luck,Seven Years Bad Luck,97995
44821,Pokémon: Spell of the Unknown,Pokémon 3: The Movie,10991
44826,Pokémon 4Ever: Celebi - Voice of the Forest,劇場版ポケットモンスター セレビィ 時を越えた遭遇（であい）,12600
45265,Force Majeure,Turist,265189

- checking if the dupliate rows have all the same info and they do!

In [77]:
clean_data.iloc[19925]

title                                                     The Congress
original_title                                            The Congress
overview             More than two decades after catapulting to sta...
original_language                                                   en
status                                                        Released
id                                                              152795
Name: 19925, dtype: str

In [78]:
clean_data.iloc[21854]

title                                                     The Congress
original_title                                            The Congress
overview             More than two decades after catapulting to sta...
original_language                                                   en
status                                                        Released
id                                                              152795
Name: 21854, dtype: str

dropping all duplicates that have almost all the columns in common, only keeping the first copy and dropping the rest.

In [79]:
clean_data.drop_duplicates(subset = ['title', 'original_title' , 'overview','id','original_language', 'status'], keep = 'first', inplace = True, ignore_index = True )

checking for duplicates of title,original title, and id since they had something in common.

In [80]:
clean_data.loc[clean_data.duplicated(keep=False), ['title', 'original_title','id']] #checking for duplicates after removing them. it shows 0

Empty DataFrame
Columns: [title, original_title, id]
Index: []

below shows we have no more duplicates!

In [81]:
print(clean_data.duplicated().sum()) #checking for duplicates. marks 0

0