In [12]:
import pandas as pd

In [13]:
df = pd.read_csv("../../data/raw/movies_metadata.csv")

/var/folders/mh/8pm0y_n52jj0jbr823sxwjfh0000gn/T/ipykernel_15021/457316574.py:1: DtypeWarning: Columns (10: popularity) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../../data/raw/movies_metadata.csv")

In [14]:
df.head()

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0

In [15]:
df.shape

(45466, 24)

In [16]:
df.dtypes

adult                        str
belongs_to_collection        str
budget                       str
genres                       str
homepage                     str
id                           str
imdb_id                      str
original_language            str
original_title               str
overview                     str
popularity                object
poster_path                  str
production_companies         str
production_countries         str
release_date                 str
revenue                  float64
runtime                  float64
spoken_languages             str
status                       str
tagline                      str
title                        str
video                     object
vote_average             float64
vote_count               float64
dtype: object

In [17]:
df.isnull().sum()

adult                        0
belongs_to_collection    40972
budget                       0
genres                       0
homepage                 37684
id                           0
imdb_id                     17
original_language           11
original_title               0
overview                   954
popularity                   5
poster_path                386
production_companies         3
production_countries         3
release_date                87
revenue                      6
runtime                    263
spoken_languages             6
status                      87
tagline                  25054
title                        6
video                        6
vote_average                 6
vote_count                   6
dtype: int64

In [18]:
df.duplicated().sum()

np.int64(13)

In [19]:
df[["id", "release_date", "budget", "revenue", "runtime", "popularity"]].head(10)

      id release_date    budget      revenue  runtime popularity
0    862   1995-10-30  30000000  373554033.0     81.0  21.946943
1   8844   1995-12-15  65000000  262797249.0    104.0  17.015539
2  15602   1995-12-22         0          0.0    101.0    11.7129
3  31357   1995-12-22  16000000   81452156.0    127.0   3.859495
4  11862   1995-02-10         0   76578911.0    106.0   8.387519
5    949   1995-12-15  60000000  187436818.0    170.0  17.924927
6  11860   1995-12-15  58000000          0.0    127.0   6.677277
7  45325   1995-12-22         0          0.0     97.0   2.561161
8   9091   1995-12-22  35000000   64350171.0    106.0    5.23158
9    710   1995-11-16  58000000  352194034.0    130.0  14.686036

In [20]:
pd.to_numeric(df["id"], errors="coerce").isna().sum()

np.int64(3)

In [21]:
pd.to_numeric(df["id"], errors="coerce").isna()

0        False
1        False
2        False
3        False
4        False
         ...
45461    False
45462    False
45463    False
45464    False
45465    False
Name: id, Length: 45466, dtype: bool

In [22]:
df[pd.to_numeric(df["id"], errors="coerce").isna()][["id", "release_date", "title"]]

               id release_date title
19730  1997-08-20            1   NaN
29503  2012-09-29           12   NaN
35587  2014-01-01           22   NaN

In [23]:
invalid_ids = df[pd.to_numeric(df["id"], errors="coerce").isna()]["id"]

invalid_ids.map(repr)

19730    '1997-08-20'
29503    '2012-09-29'
35587    '2014-01-01'
Name: id, dtype: str

In [24]:
df.loc[invalid_ids.index, ["id", "release_date", "title"]]

               id release_date title
19730  1997-08-20            1   NaN
29503  2012-09-29           12   NaN
35587  2014-01-01           22   NaN

In [27]:
invalid_id_mask = pd.to_numeric(df["id"], errors="coerce").isna()

df = df.loc[~invalid_id_mask].copy()

In [28]:
pd.to_numeric(df["id"], errors="coerce").isna().sum()

np.int64(0)

In [29]:
df.shape

(45463, 24)

In [30]:
df["id"] = pd.to_numeric(df["id"])

In [31]:
df["id"].dtype

dtype('int64')

# ID Movie Cleaning: 3 records contained dates in the 'id' column instead of valid numeric movie IDs. The records were removed because a valid movie ID is required in order to identify each movie and remaining IDs were converted to numeric data type.

In [32]:
pd.to_datetime(df["release_date"], errors="coerce").isna().sum()

np.int64(87)

In [33]:
df["release_date"] = pd.to_datetime(
    df["release_date"],
    errors="coerce"
)

In [34]:
df["release_date"].dtype

dtype('<M8[us]')

In [35]:
df["release_date"].isna().sum()

np.int64(87)

In [36]:
df["budget"].head(10)

0    30000000
1    65000000
2           0
3    16000000
4           0
5    60000000
6    58000000
7           0
8    35000000
9    58000000
Name: budget, dtype: str

In [41]:
pd.to_numeric(df["budget"], errors="coerce").isna().sum()

np.int64(0)

In [42]:
df["budget"] = pd.to_numeric(df["budget"], errors="coerce")

In [43]:
df["budget"].dtype

dtype('int64')

In [44]:
(df["budget"] == 0).sum()

np.int64(36573)

In [45]:
(df["budget"] < 0).sum()

np.int64(0)

# Cleaning budget: The budget column was converted from strings to numeric type. There were 36,573 records with a budget of 0 and no records with negative budgets. rows with zero budgets were retained since they were seen as unknown values rather than invalid records for movies.

In [46]:
df["revenue"].dtype

dtype('float64')

In [47]:
pd.to_numeric(df["revenue"], errors="coerce").isna().sum()

np.int64(3)

In [48]:
(df["revenue"] == 0).sum()

np.int64(38052)

In [49]:
(df["revenue"] < 0).sum()

np.int64(0)

In [50]:
df["revenue"] = pd.to_numeric(df["revenue"], errors="coerce")

# Cleaning revenue: The revenue column was already stored as numerical float 64 type, there were 3 missing/invalid values, no negative revenue values, 38,052 records with revenue equal to 0. The zero values were treated as unkown/suspicious rather than invalid movie records, so rows were retained.

In [51]:
df["runtime"].dtype

dtype('float64')

In [53]:
pd.to_numeric(df["runtime"], errors="coerce").isna().sum()

np.int64(260)

In [55]:
(df["runtime"] <= 0).sum()

np.int64(1558)

In [56]:
(df["runtime"] == 0).sum()

np.int64(1558)

In [57]:
(df["runtime"] < 0).sum()

np.int64(0)

In [58]:
df.loc[df["runtime"] <= 0, "runtime"] = pd.NA

In [59]:
df["runtime"].isna().sum()

np.int64(1818)

# Cleaing runtime: The runtime column was already in numeric float 64 type. There were 260 missing values, 1,558 values equal to 0. 0 values were converted to missign values and the rest were kept.

In [60]:
df["popularity"].dtype

dtype('O')

In [61]:
pd.to_numeric(df["popularity"], errors="coerce").isna().sum()

np.int64(3)

In [62]:
df["popularity"] = pd.to_numeric(df["popularity"], errors="coerce")

In [63]:
df["popularity"].dtype

dtype('float64')

In [65]:
(df["popularity"] < 0).sum()

np.int64(0)

# Cleaning popularity: The popularity column was initially stored as an object type and then was converted to numeric float 64 type. 3 values couldn't be converted to numbers and were treated as missing values. There was no negative values and no additional things were removed.

In [66]:
df.duplicated().sum()

np.int64(17)

In [67]:
df = df.drop_duplicates()

In [68]:
df.duplicated().sum()

np.int64(0)

In [69]:
df["id"].duplicated().sum()

np.int64(13)

In [70]:
df[df["id"].duplicated(keep=False)].sort_values("id")

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
33826,False,NaN,30000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 80, 'nam...",NaN,4912,tt0270288,en,Confessions of a Dangerous Mind,"Television made him famous, but his biggest hi...",...,2002-12-30,33013805.0,113.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Some things are better left top secret.,Confessions of a Dangerous Mind,False,6.6,281.0
5865,False,NaN,30000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 80, 'nam...",NaN,4912,tt0270288,en,Confessions of a Dangerous Mind,"Television made him famous, but his biggest hi...",...,2002-12-30,33013805.0,113.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Some things are better left top secret.,Confessions of a Dangerous Mind,False,6.6,281.0
4114,False,"{'id': 34055, 'name': 'Pokémon Collection', 'p...",16000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",http://movies.warnerbros.com/pk3/,10991,tt0235679,ja,Pokémon 3: The Movie,When Molly Hale's sadness of her father's disa...,...,2000-07-08,68411275.0,93.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Pokémon: Spell of the Unknown,Pokémon: Spell of the Unknown,False,6.0,143.0
44821,False,"{'id': 34055, 'name': 'Pokémon Collection', 'p...",16000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",http://movies.warnerbros.com/pk3/,10991,tt0235679,ja,Pokémon 3: The Movie,When Molly Hale's sadness of her father's disa...,...,2000-07-08,68411275.0,93.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Pokémon: Spell of the Unknown,Pokémon: Spell of the Unknown,False,6.0,144.0
44826,False,"{'id': 34055, 'name': 'Pokémon Collection', 'p...",0,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",http://www.pokemon.com/us/movies/movie-pokemon...,12600,tt0287635,ja,劇場版ポケットモンスター セレビィ 時を越えた遭遇（であい）,"All your favorite Pokémon characters are back,...",...,2001-07-06,28023563.0,75.0,"[{'iso_639_1': 'ja', 'name': '日本語'}]",Released,NaN,Pokémon 4Ever: Celebi - Voice of the Forest,False,5.7,82.0
5535,False,"{'id': 34055, 'name': 'Pokémon Collection', 'p...",0,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",http://www.pokemon.com/us/movies/movie-pokemon...,12600,tt0287635,ja,劇場版ポケットモンスター セレビィ 時を越えた遭遇（であい）,"All your favorite Pokémon characters are back,...",...,2001-07-06,28023563.0,75.0,"[{'iso_639_1': 'ja', 'name': '日本語'}]",Released,NaN,Pokémon 4Ever: Celebi - Voice of the Forest,False,5.7,82.0
15765,False,NaN,2500,"[{'id': 18, 'name': 'Drama'}, {'id': 35, 'name...",NaN,13209,tt0499537,fa,Offside,"Since women are banned from soccer matches, Ir...",...,2006-05-26,0.0,93.0,"[{'iso_639_1': 'fa', 'name': 'فارسی'}]",Released,NaN,Offside,False,6.7,27.0
11342,False,NaN,2500,"[{'id': 18, 'name': 'Drama'}, {'id': 35, 'name...",NaN,13209,tt0499537,fa,Offside,"Since women are banned from soccer matches, Ir...",...,2006-05-26,0.0,93.0,"[{'iso_639_1': 'fa', 'name': 'فارسی'}]",Released,NaN,Offside,False,6.7,27.0
10419,False,NaN,1600000,"[{'id': 18, 'name': 'Drama'}, {'id': 80, 'name...",http://www.bubblethefilm.com/,14788,tt0454792,en,Bubble,Set against the backdrop of a decaying Midwest...,...,2005-09-03,0.0,73.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Bubble,False,6.4,36.0
12066,False,NaN,1600000,"[{'id': 18, 'name': 'Drama'}, {'id': 80, 'name...",http://www.bubblethefilm.com/,14788,tt0454792,en,Bubble,Set against the backdrop of a decaying Midwest...,...,2005-09-03,0.0,73.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Bubble,False,6.4,36.0
5130,False,NaN,26000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 10751...",NaN,15028,tt0157472,en,Clockstoppers,"Until now, Zak Gibbs' greatest challenge has b...",...,2002-03-17,38793283.0,94.0,"[{'iso_639_1': 'cs', 'name': 'Český'}, {'iso_6...",Released,"The adventure of a lifetime, in a few mere sec...",Clockstoppers,False,4.9,89.0
33743,False,NaN,26000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 10751...",NaN,15028,tt0157472,en,Clockstoppers,"Until now, Zak Gibbs' greatest challenge has b...",...,2002-03-17,38793283.0,94.0,"[{'iso_639_1': 'cs', 'name': 'Český'}, {'iso_6...",Released,"The adventure of a lifetime, in a few mere sec...",Clockstoppers,False,4.9,90.0
949,False,NaN,4,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",NaN,22649,tt0022879,en,A Farewell to Arms,British nurse Catherine Barkley (Helen Hayes) ...,...,1932-12-08,25.0,89.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Every woman who has loved will understand,A Farewell to Arms,False,6.2,29.0
15074,False,NaN,4,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",NaN,22649,tt0022879,en,A Farewell to Arms,British nurse Catherine Barkley (Helen Hayes) ...,...,1932-12-08,25.0,89.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Every woman who has loved will understand,A Farewell to Arms,False,6.2,29.0
9576,False,NaN,10000000,"[{'id': 18, 'name': 'Drama'}, {'id': 27, 'name...",NaN,69234,tt0100361,en,The Phantom of the Opera,Count de Chagnie has discovered Christine's si...,...,1990-03-18,0.0,168.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,NaN,The Phantom of the Opera,False,5.0,3.0
26625,False,NaN,10000000,"[{'id': 18, 'name': 'Drama'}, {'id': 27, 'name...",NaN,69234,tt0100361,en,The Phantom of the Opera,Count de Chagnie has discovered Christine's si...,...,1990-03-18,0.0,168.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,NaN,The Phantom of the Opera,False,5.0,3.0
20843,False,NaN,40000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 18, '...",NaN,77221,tt1701210,en,Black Gold,"On the Arabian Peninsula in the 1930s, two war...",...,2011-12-21,5446000.0,130.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Black Gold,False,5.9,77.0
11155,False,NaN,40000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 18, '...",NaN,77221,tt1701210,en,Black Gold,"On the Arabian Peninsula in the 1930s, two war...",...,2011-12-21,5446000.0,130.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Black Gold,False,5.9,77.0
21116,False,NaN,0,"[{'id': 99, 'name': 'Documentary'}]",NaN,84198,tt1736049,en,A Place at the Table,"Using personal stories, this powerful document...",...,2012-03-22,0.0,84.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,One Nation. Underfed.,A Place at the Table,False,6.9,7.0
2564,False,NaN,0,"[{'id': 99, 'name': 'Documentary'}]",NaN,84198,tt1736049,en,A Place at the Table,"Using personal stories, this powerful document...",...,2012-03-22,0.0,84.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,One Nation. Underfed.,A Place at the Table,False,6.9,7.0
20899,False,NaN,0,"[{'id': 18, 'name': 'Drama'}]",NaN,109962,tt0082992,en,Rich and Famous,Two literary women compete for 20 years: one w...,...,1981-09-23,0.0,115.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,"From the very beginning, they knew they'd be f...",Rich and Famous,False,4.9,7.0
5710,False,NaN,0,"[{'id': 18, 'name': 'Drama'}]",NaN,109962,tt0082992,en,Rich and Famous,Two literary women compete for 20 years: one w...,...,1981-09-23,0.0,115.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,"From the very beginning, they knew they'd be f...",Rich and Famous,False,4.9,7.0
23534,False,NaN,3512454,"[{'id': 18, 'name': 'Drama'}]",NaN,110428,tt2018086,fr,Camille Claudel 1915,"Winter, 1915. Confined by her family to an asy...",...,2013-03-13,115860.0,95.0,"[{'iso_639_1': 'fr', 'name': 'Français'}]",Released,NaN,Camille Claudel 1915,False,7.0,20.0
4356,False,NaN,3512454,"[{'id': 18, 'name': 'Drama'}]",NaN,110428,tt2018086,fr,Camille Claudel 1915,"Winter, 1915. Confined by her family to an asy...",...,2013-03-13,115860.0,95.0,"[{'iso_639_1': 'fr', 'name': 'Français'}]",Released,NaN,Camille Claudel 1915,False,7.0,20.0
30001,False,NaN,0,"[{'id': 18, 'name': 'Drama'}]",NaN,132641,tt0046468,ja,Tsuma,"Ten years into a marriage, the wife is disappo...",...,1953-04-29,0.0,89.0,"[{'iso_639_1': 'ja', 'name': '日本語'}]",Released,NaN,Wife,False,0.0,0.0
838,False,NaN,0,"[{'id': 18, 'name': 'Drama'}]",NaN,132641,tt0046468,ja,Tsuma,"Ten years into a marriage, the wife is disappo...",...,1953-04-29,0.0,89.0,"[{'iso_639_1': 'ja', 'name': '日本語'}]",Released,NaN,Wife,False,0.0,0.0

In [71]:
df = df.drop_duplicates(subset=["id"], keep="first")

In [72]:
df["id"].duplicated().sum()

np.int64(0)

# Removing duplicate movie IDs: After removing exact duplicate rows, 13 movie IDs remained. Some duplicate IDs had a little different values in other columns but they represented the same movie. The first of each movie ID was kept.

In [73]:
df = df[
    [
        "id",
        "release_date",
        "budget",
        "revenue",
        "runtime",
        "popularity"
    ]
]

In [74]:
df.columns

Index(['id', 'release_date', 'budget', 'revenue', 'runtime', 'popularity'], dtype='str')

In [75]:
df.shape

(45433, 6)

In [77]:
df.dtypes

id                       int64
release_date    datetime64[us]
budget                   int64
revenue                float64
runtime                float64
popularity             float64
dtype: object

In [78]:
df.isnull().sum()

id                 0
release_date      87
budget             0
revenue            3
runtime         1818
popularity         3
dtype: int64

In [79]:
df.duplicated().sum()

np.int64(0)

In [82]:
df["id"].duplicated().sum()

np.int64(0)

# Dataset: The final processed dataset contains 45,433 rows and 6 coluumns. 0 exact duplicate rows and movie Ids remain. The final database only contains id, release_date, budget, revenue, runtime, and popularity.

In [87]:
df.to_csv("../../data/processed/movies_metadata.csv", index=False)